functions:
    auth-manager:
        handler: auth-manager-server.auth # reference the file and exported method
        package:
            include:
                - "auth-manager-server.js"
        events: # events trigger lambda functions
            - http:
                path: /auth
                method: POST
                cors: true
            - http:
                path: /auth/health
                method: GET
                cors: true