functions:
  order-manager:
    handler: order-manager-server.order # reference the file and exported method
     package:
        include:
          - "order-manager-server.js"
    events: # events trigger lambda functions
      - http:
          path: /order/health
          method: GET
          cors: true
      - http:
          path: /order/{id}
          method: GET
          cors: true
      - http:
          path: /orders
          method: GET
          cors: true
      - http:
          path: /order
          method: POST
          cors: true
      - http:
          path: /order
          method: PUT
          cors: true
      - http:
          path: /order/{id}
          method: DELETE
          cors: true