functions:
  product-manager:
    handler: product-manager-server.product # reference the file and exported method
    package:
      include:
        - "product-manager-server.js"
    events: # events trigger lambda functions
      - http:
          path: /product/health
          method: GET
          cors: true
      - http:
          path: /product/{id}
          method: GET
          cors: true
      - http:
          path: /products
          method: GET
          cors: true
      - http:
          path: /products
          method: POST
          cors: true
      - http:
          path: /products
          method: PUT
          cors: true
      - http:
          path: /product/{id}
          method: DELETE
          cors: true