functions:
  system-reg:
    handler: system-reg-server.sys # reference the file and exported method
     package:
      include:
        - "system-reg-server.js"
    events: # events trigger lambda functions
      - http:
          path: /sys/admin
          method: POST
          cors: true
      - http:
          path: /sys/admin
          method: DELETE
          cors: true