functions:
  tenant-manager:
    handler: tenant-manager-server.tenant # reference the file and exported method
     package:
        include:
          - "tenant-manager-server.js"
    events: # events trigger lambda functions
      - http:
          path: /tenant/health
          method: GET
          cors: true
      - http:
          path: /tenant/{id}
          method: GET
          cors: true
      - http:
          path: /tenants
          method: GET
          cors: true
      - http:
          path: /tenants/system
          method: GET
          cors: true
      - http:
          path: /tenant
          method: POST
          cors: true
      - http:
          path: /tenant
          method: PUT
          cors: true
      - http:
          path: /tenant/{id}
          method: DELETE
          cors: true