functions:
  tenant-reg:
    handler: tenant-reg-server.reg # reference the file and exported method
    package:
      include:
        - "tenant-reg-server.js"
    events: # events trigger lambda functions
      - http:
          path: /reg
          method: POST
          cors: true
      - http:
          path: /reg/health
          method: GET
          cors: true