functions:
  user-manager:
    handler: user-manager-server.user # reference the file and exported method
    package:
      include:
        - "user-manager-server.js"
    events: # events trigger lambda functions
      - http:
          path: /user/health
          method: GET
          cors: true
      - http:
          path: /user/tables
          method: DELETE
          cors: true
      - http:
          path: /user/tenants
          method: DELETE
          cors: true
      - http:
          path: /user/pool/{id}
          method: GET
          cors: true
      - http:
          path: /user/{id}
          method: GET
          cors: true
      - http:
          path: /users
          method: GET
          cors: true
      - http:
          path: /user
          method: POST
          cors: true
      - http:
          path: /user/system
          method: POST
          cors: true
      - http:
          path: /user/reg
          method: POST
          cors: true
      - http:
          path: /user/enable
          method: PUT
          cors: true
      - http:
          path: /user/disable
          method: PUT
          cors: true
      - http:
          path: /user
          method: PUT
          cors: true
      - http:
          path: /user/{id}
          method: DELETE
          cors: true